create sequence seq_categoria_produto start 1 increment 1;
create sequence seq_edital start 1 increment 1;
create sequence seq_empresa start 1 increment 1;
create sequence seq_endereco start 1 increment 1;
create sequence seq_grupo start 1 increment 1;
create sequence seq_imagem_produto start 1 increment 1;
create sequence seq_leilao start 1 increment 1;
create sequence seq_marca_produto start 1 increment 1;
create sequence seq_produto start 1 increment 1;
create sequence seq_usuario start 1 increment 1;
create table categoria_produto (id int8 not null, ativo boolean not null, codigo_usuario_criacao int8, codigo_usuario_modificacao int8, criacao timestamp not null, modificacao timestamp, nome_desc varchar(255) not null, primary key (id));
create table edital (id int8 not null, ativo boolean not null, codigo_usuario_criacao int8, codigo_usuario_modificacao int8, criacao timestamp not null, modificacao timestamp, data_fim timestamp, data_inicio timestamp, numero int8 not null, titulo varchar(255), empresa_id int8 not null, endereco_id int8 not null, primary key (id));
create table edital_produtos (edital_id int8 not null, produto_id int8 not null, primary key (edital_id, produto_id));
create table endereco (id int8 not null, ativo boolean not null, codigo_usuario_criacao int8, codigo_usuario_modificacao int8, criacao timestamp not null, modificacao timestamp, bairro varchar(255) not null, cep varchar(255) not null, cidade varchar(255) not null, complemento varchar(255), estado varchar(255), numero varchar(255) not null, rua_logra varchar(255) not null, tipo_endereco varchar(255), primary key (id));
create table imagem_produto (id int8 not null, ativo boolean not null, codigo_usuario_criacao int8, codigo_usuario_modificacao int8, criacao timestamp not null, modificacao timestamp, imagem_miniatura text not null, imagem_original text not null, usuario_id int8 not null, produto_id int8 not null, primary key (id));
create table leilao (id int8 not null, ativo boolean not null, codigo_usuario_criacao int8, codigo_usuario_modificacao int8, criacao timestamp not null, modificacao timestamp, valor_lance numeric(19, 2), edital_id int8 not null, usuario_id int8 not null, primary key (id));
create table marca_produto (id int8 not null, ativo boolean not null, codigo_usuario_criacao int8, codigo_usuario_modificacao int8, criacao timestamp not null, modificacao timestamp, nome_desc varchar(255) not null, primary key (id));
create table produto (id int8 not null, ativo boolean not null, codigo_usuario_criacao int8, codigo_usuario_modificacao int8, criacao timestamp not null, modificacao timestamp, alerta_qtde_estoque boolean, altura float8 not null, descricao text not null, largura float8 not null, link_youtube varchar(255), nome varchar(255) not null, peso float8 not null, profundidade float8 not null, qtd_estoque int4 not null, qtde_alerta_estoque int4, qtde_clique int4, tipo_unidade varchar(255) not null, valor_venda numeric(19, 2) not null, categoria_produto_id int8 not null, empresa_id int8 not null, marca_produto_id int8 not null, primary key (id));
create table tb_empresas (id int8 not null, ativo boolean not null, codigo_usuario_criacao int8, codigo_usuario_modificacao int8, criacao timestamp not null, modificacao timestamp, categoria varchar(255), cnpj varchar(255) not null, insc_estadual varchar(255) not null, insc_municipal varchar(255), nome_fantasia varchar(50) not null, razao_social varchar(255) not null, telefone varchar(255), endereco_id int8, primary key (id));
create table tb_grupos (id int8 not null, ativo boolean not null, codigo_usuario_criacao int8, codigo_usuario_modificacao int8, criacao timestamp not null, modificacao timestamp, nome varchar(30) not null, primary key (id));
create table tb_usuarios (id int8 not null, ativo boolean not null, codigo_usuario_criacao int8, codigo_usuario_modificacao int8, criacao timestamp not null, modificacao timestamp, email varchar(255) not null, password varchar(255) not null, status_usuario varchar(255), telefone varchar(255), tipo_usuario varchar(255), username varchar(255), empresa_id int8 not null, primary key (id));
create table tb_usuarios_grupos (usuario_id int8 not null, grupo_id int8 not null, primary key (usuario_id, grupo_id));
alter table tb_empresas add constraint UK_9ubgjwwk9fig4j9rcdnhq3nea unique (nome_fantasia);
alter table tb_empresas add constraint UK_ox5970btpxvjcv8ru8y4072bd unique (razao_social);
alter table tb_grupos add constraint UK_p7q0fq0sermy36uhhvqcop173 unique (nome);
alter table edital add constraint empresa_id_fk foreign key (empresa_id) references tb_empresas;
alter table edital add constraint endereco_id_fk foreign key (endereco_id) references endereco;
alter table edital_produtos add constraint FKsrky02fx259il0gkxp2e6qh3p foreign key (produto_id) references produto;
alter table edital_produtos add constraint FKrd8ipjg2e4ks8fnahnpewe6gk foreign key (edital_id) references edital;
alter table imagem_produto add constraint usuario_id_fk foreign key (usuario_id) references tb_usuarios;
alter table imagem_produto add constraint produto_fk foreign key (produto_id) references produto;
alter table leilao add constraint edital_id_fk foreign key (edital_id) references edital;
alter table leilao add constraint usuario_id_fk foreign key (usuario_id) references tb_usuarios;
alter table produto add constraint categoria_produto_id_fk foreign key (categoria_produto_id) references categoria_produto;
alter table produto add constraint empresa_id_fk foreign key (empresa_id) references tb_empresas;
alter table produto add constraint marca_produto_id_fk foreign key (marca_produto_id) references marca_produto;
alter table tb_empresas add constraint endereco_id_fk foreign key (endereco_id) references endereco;
alter table tb_usuarios add constraint empresa_fk foreign key (empresa_id) references tb_empresas;
alter table tb_usuarios_grupos add constraint FKfibqpkrm4y3jn1tbk4vyg06o8 foreign key (grupo_id) references tb_grupos;
alter table tb_usuarios_grupos add constraint FK6y5q1pf4as1blfkq1fikyxt61 foreign key (usuario_id) references tb_usuarios;