name: CICD

on:
  push:
    branches: [deploy-to-ec2]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build -t jhonnyscerni/mercado-negocios .
      - name: Publish image to docker hub
        run: docker push jhonnyscerni/mercado-negocios:latest

  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Pull Image from docker hub
        run: sudo docker pull jhonnyscerni/mercado-negocios:latest
      - name: Delete old container
        run: sudo docker rm -f /mercado-negocios-container
      - name: Run docker container
        run: sudo docker run -d -p 8080:8080 --name mercado-negocios-container jhonnyscerni/mercado-negocios